up:
	cd "../laradock" && docker-compose up -d nginx mysql workspace
work:
	cd "../laradock" && docker-compose exec workspace bash
down:
	cd "../laradock" && docker-compose down
ps:
	cd "../laradock" && docker-compose ps
stop:
	cd "../laradock" && docker-compose stop
open:
	open http://localhost